### ISSUE TITLE
lamigra.js add state variable called "alive" or "vivo" to each NPC member of cacahuates

### ISSUE THREAD

**Issue by rafaelfajardo** [rafaelfajardo/border-games-rewrite#169]
Need to add a boolean state variable to each Non Player Character member of the group called cacahuates. The variable can be named in English, "alive", or in Spanish, "vivo". The default state is TRUE. If an individual member of cacahuates is overlapped by the Migra car then the state changes to FALSE (!vivo or !alive). The consequence of the state change is that the death mask image is displayed for the particular sprite, movement for the sprite stops, and the sprite becomes immovable. The collision detection between the Migra car and members of cacahuates is the subject of another issue.

Groups are a feature of Play.P5.js that behave similar to an array and similar to class. We can perform logic on a group in the aggregate and on individual members. We have created a group called cacahuates with members that represent people (not set pieces)

**Comment by chrisgd** [comment]
Added an isDead (could be called esMuerto?) instead just because of the way I was thinking about things like animations (if sprite.isDead then don't animate) which when I think about it is a double negative, haha. Also done in #331
