### ISSUE TITLE
lamigra.js add collision detection between Migra car and NPC members of cacahuates group

### ISSUE THREAD

**Issue by rafaelfajardo** [rafaelfajardo/border-games-rewrite#170]
Need to add collision detection between Player Character sprite "migra" and any Non Player Character sprite that is a member of the cacahuates group. Any overlap between migra and cacahuates[index] should change the state of the NPC member variable "vivo/alive" to FALSE or !TRUE, and consequently change it's appearance and direction/speed to zero (0), it's collider should prevent migra from running over it or past it.

Groups are a feature of Play.P5.js that behave similar to an array and similar to class. We can perform logic on a group in the aggregate and on individual members. We have created a group called cacahuates with members that represent people (not set pieces)

**Comment by chrisgd** [comment]
Added in #231, which has the collision detection with NPCs, animations for it. They stop and no longer move after being run over. In addition, NPCs no longer walk over signs and the car is animated
